// This file is automatically generated. Do not edit it directly.
import { createClient, type SupportedStorage } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "placeholder-key";
const browserStorage: SupportedStorage | undefined =
  typeof window !== 'undefined' ? window.localStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserStorage,
    persistSession: Boolean(browserStorage),
    autoRefreshToken: true,
    detectSessionInUrl: false,
  }
});
